import{useMemo,useState}from"react";import{scenarios}from"./data/scenarios";import{ConversationState,Message,TurnAnalysis}from"./domain/types";import{analyzeTurn}from"./engine/analyze";import{updateState}from"./engine/state";import{generateRuleBasedReply}from"./engine/reply";import{buildFeedback}from"./engine/feedback";
const names:Record<keyof ConversationState,string>={trust:"信頼",readiness:"行動準備性",resistance:"抵抗",selfEfficacy:"自己効力感",disclosure:"情報開示",concern:"健康への関心"};
export default function App(){const[id,setId]=useState(scenarios[0].id);const s=useMemo(()=>scenarios.find(x=>x.id===id)??scenarios[0],[id]);const[m,setM]=useState<Message[]>([]);const[a,setA]=useState<TurnAnalysis[]>([]);const[st,setSt]=useState<ConversationState>(s.initialState);const[input,setInput]=useState("");const[done,setDone]=useState(false);
const reset=(next=id)=>{const x=scenarios.find(v=>v.id===next)??scenarios[0];setM([{role:"client",text:x.persona.representativeUtterance}]);setA([]);setSt(x.initialState);setDone(false);setInput("")};
const choose=(v:string)=>{setId(v);reset(v)};const send=()=>{const t=input.trim();if(!t||done)return;const x=analyzeTurn(t),ns=updateState(st,x),r=generateRuleBasedReply(s,ns,x,a.length+1);setM(v=>[...v,{role:"phn",text:t},{role:"client",text:r}]);setA(v=>[...v,x]);setSt(ns);setInput("")};const fb=done?buildFeedback(m,a):null;
return <main className="app"><header className="hero"><div><p className="eyebrow">G-CHAM / Public Health Nursing Simulation</p><h1>G-CHAM PHN Conversation Trainer</h1><p>特定保健指導の対象者との対話を、対象者背景と会話状態の変化を踏まえて練習する教育用プロトタイプです。</p></div><span className="badge">MVP 0.1</span></header>
<section className="panel"><label>ケース</label><select value={id} onChange={e=>choose(e.target.value)}>{scenarios.map(x=><option key={x.id} value={x.id}>{x.difficulty}｜{x.title}</option>)}</select><div className="grid"><div><h2>{s.title}</h2><p>{s.supportType}・{s.difficulty}</p><ul>{s.publicContext.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>学習目標</h3><ul>{s.learningObjectives.map(x=><li key={x}>{x}</li>)}</ul></div></div></section>
<section className="workspace"><div className="panel"><div className="head"><h2>会話</h2><button className="secondary" onClick={()=>reset()}>最初から</button></div>{!m.length?<div className="empty"><button onClick={()=>reset()}>トレーニング開始</button></div>:<div className="messages">{m.map((x,i)=><div key={i} className={"msg "+x.role}><small>{x.role==="phn"?"保健師":"対象者"}</small><p>{x.text}</p></div>)}</div>}{!done&&m.length>0&&<><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="対象者に話しかけてください" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><div className="actions"><button onClick={send}>送信</button><button className="secondary" onClick={()=>setDone(true)}>面接を終了して振り返る</button></div></>}</div>
<aside className="panel"><h2>トレーニング中の状態</h2><p className="small">教育用の内部モデルであり心理尺度ではありません。</p>{(Object.keys(st)as(keyof ConversationState)[]).map(k=><div className="metric" key={k}><div><span>{names[k]}</span><span>{st[k]}</span></div><progress max="100" value={st[k]}/></div>)}<h3>対象者背景</h3><p>{s.persona.age}歳・{s.persona.sex}／{s.persona.occupation}</p><p>{s.persona.exercise}／{s.persona.diet}</p></aside></section>
{fb&&<section className="panel feedback"><h2>振り返り</h2><div className="grid3"><div><h3>できていた点</h3><ul>{fb.strengths.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>改善できる点</h3><ul>{fb.improvements.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>未確認・次の課題</h3><ul>{fb.unresolved.map(x=><li key={x}>{x}</li>)}</ul></div></div></section>}<footer>参考設計：厚生労働省「標準的な健診・保健指導プログラム（令和6年度版）」。JMED-Personas利用時はCC BY 4.0に基づき出典を表示します。</footer></main>}